name: 🐍 Generate Snake Animation

on:
  workflow_dispatch:      # você pode rodar manualmente
  schedule:
    - cron: "0 3 * * *"   # roda todo dia às 3h UTC

permissions:
  contents: write         # permite commitar no repositório

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout do repositório
        uses: actions/checkout@v4

      - name: 🔐 Marcar workspace como seguro
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: 🐍 Gerar animação Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: fiamaribeiro
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: 🚀 Commit e push dos arquivos
        run: |
          ls -R
          git status

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add dist/github-contribution-grid-snake*.svg || true

          if git diff --cached --quiet; then
            echo "Nenhuma alteração para commitar."
          else
            git commit -m "chore: update snake animation"
            git push
          fi
